### ISSUE TITLE
Add prometheus configuration

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/networks#2]
We should add somewhere the default config file to start prometheus.

Details on how to run it n the PR https://github.com/mesg-foundation/engine/pull/1580

```yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'testnet'
    scrape_interval: 15s
    static_configs:
      - targets: ['engine:26660']
        labels:
          instance: 'engine'
```
